// Material 3 Expressive web components (M3E) used across the app + Material Symbols icons as SVG modules.
import '@m3e/web/theme';
import '@m3e/web/icon';
import '@m3e/web/button';
import '@m3e/web/icon-button';
import '@m3e/web/fab';
import '@m3e/web/chips';
import '@m3e/web/nav-bar';
import '@m3e/web/nav-rail';
import '@m3e/web/app-bar';
import '@m3e/web/slider';
import '@m3e/web/dialog';
import '@m3e/web/menu';
import '@m3e/web/list';
import '@m3e/web/search';
import '@m3e/web/snackbar';
import '@m3e/web/card';
import '@m3e/web/tabs';
import '@m3e/web/loading-indicator';
import '@m3e/web/progress-indicator';
import '@m3e/web/switch';
import '@m3e/web/segmented-button';
import '@m3e/web/tooltip';
import '@m3e/web/avatar';
import '@m3e/web/heading';
import '@m3e/web/badge';
import '@m3e/web/shape';
import '@m3e/web/bottom-sheet';
import '@m3e/web/skeleton';
import '@m3e/web/divider';
import '@m3e/web/form-field';
import '@m3e/web/select';
import '@m3e/web/option';

// Icons (rounded variant): each import registers the SVG with <m3e-icon name="…">
import '@m3e/icons/rounded/home';
import '@m3e/icons/rounded/search';
import '@m3e/icons/rounded/library_music';
import '@m3e/icons/rounded/download';
import '@m3e/icons/rounded/shield';
import '@m3e/icons/rounded/person';
import '@m3e/icons/rounded/settings';
import '@m3e/icons/rounded/play_arrow';
import '@m3e/icons/rounded/pause';
import '@m3e/icons/rounded/skip_next';
import '@m3e/icons/rounded/skip_previous';
import '@m3e/icons/rounded/shuffle';
import '@m3e/icons/rounded/repeat';
import '@m3e/icons/rounded/repeat_one';
import '@m3e/icons/rounded/volume_up';
import '@m3e/icons/rounded/volume_down';
import '@m3e/icons/rounded/volume_off';
import '@m3e/icons/rounded/favorite';
import '@m3e/icons/rounded/more_vert';
import '@m3e/icons/rounded/more_horiz';
import '@m3e/icons/rounded/queue_music';
import '@m3e/icons/rounded/lyrics';
import '@m3e/icons/rounded/close';
import '@m3e/icons/rounded/keyboard_arrow_down';
import '@m3e/icons/rounded/keyboard_arrow_up';
import '@m3e/icons/rounded/chevron_left';
import '@m3e/icons/rounded/chevron_right';
import '@m3e/icons/rounded/arrow_back';
import '@m3e/icons/rounded/arrow_forward';
import '@m3e/icons/rounded/add';
import '@m3e/icons/rounded/add_circle';
import '@m3e/icons/rounded/check';
import '@m3e/icons/rounded/check_circle';
import '@m3e/icons/rounded/offline_pin';
import '@m3e/icons/rounded/cloud_download';
import '@m3e/icons/rounded/delete';
import '@m3e/icons/rounded/edit';
import '@m3e/icons/rounded/upload';
import '@m3e/icons/rounded/link';
import '@m3e/icons/rounded/refresh';
import '@m3e/icons/rounded/album';
import '@m3e/icons/rounded/artist';
import '@m3e/icons/rounded/playlist_add';
import '@m3e/icons/rounded/playlist_play';
import '@m3e/icons/rounded/dark_mode';
import '@m3e/icons/rounded/light_mode';
import '@m3e/icons/rounded/palette';
import '@m3e/icons/rounded/fullscreen';
import '@m3e/icons/rounded/share';
import '@m3e/icons/rounded/radio';
import '@m3e/icons/rounded/bedtime';
import '@m3e/icons/rounded/speed';
import '@m3e/icons/rounded/public';
import '@m3e/icons/rounded/explore';
import '@m3e/icons/rounded/graphic_eq';
import '@m3e/icons/rounded/music_note';
import '@m3e/icons/rounded/logout';
import '@m3e/icons/rounded/login';
import '@m3e/icons/rounded/key';
import '@m3e/icons/rounded/notifications';
import '@m3e/icons/rounded/notifications_active';
import '@m3e/icons/rounded/sync';
import '@m3e/icons/rounded/warning';
import '@m3e/icons/rounded/add_a_photo';
import '@m3e/icons/rounded/photo_camera';
import '@m3e/icons/rounded/photo_library';
import '@m3e/icons/rounded/zoom_in';
import '@m3e/icons/rounded/zoom_out';
import '@m3e/icons/rounded/person_add';
import '@m3e/icons/rounded/how_to_reg';
import '@m3e/icons/rounded/timer_off';
import '@m3e/icons/rounded/content_copy';
import '@m3e/icons/rounded/image';
import '@m3e/icons/rounded/cancel';
import '@m3e/icons/rounded/error';
import '@m3e/icons/rounded/info';
import '@m3e/icons/rounded/history';
import '@m3e/icons/rounded/mic';
import '@m3e/icons/rounded/movie';
import '@m3e/icons/rounded/drag_handle';
import '@m3e/icons/rounded/headphones';
import '@m3e/icons/rounded/star';
import '@m3e/icons/rounded/download_for_offline';
import '@m3e/icons/rounded/category';
import '@m3e/icons/rounded/search_off';
import '@m3e/icons/rounded/remove';
import '@m3e/icons/rounded/equalizer';
import '@m3e/icons/rounded/open_in_new';
import '@m3e/icons/rounded/folder_open';
import '@m3e/icons/rounded/stars';
import '@m3e/icons/rounded/verified';
import '@m3e/icons/rounded/schedule';
import '@m3e/icons/rounded/menu';
import '@m3e/icons/rounded/menu_open';
import '@m3e/icons/rounded/star';
import '@m3e/icons/rounded/download_for_offline';
import '@m3e/icons/rounded/wifi_off';
import '@m3e/icons/rounded/lock';
import '@m3e/icons/rounded/group';
import '@m3e/icons/rounded/bar_chart';
import '@m3e/icons/rounded/format_color_fill';
import '@m3e/icons/rounded/translate';
import '@m3e/icons/rounded/hourglass_empty';
import '@m3e/icons/rounded/playlist_remove';
import '@m3e/icons/rounded/cloud_off';

export { M3eSnackbar } from '@m3e/web/snackbar';
export { getColorFromImage } from '@m3e/web/theme';
export type { ThemeVariant, ColorScheme } from '@m3e/web/theme';

// React bindings
export { M3eTheme, M3eThemeIcon } from '@m3e/react/theme';
export { M3eButton } from '@m3e/react/button';
export { M3eIconButton } from '@m3e/react/icon-button';
export { M3eFab } from '@m3e/react/fab';
export { M3eAssistChip, M3eFilterChip, M3eFilterChipSet, M3eChipSet, M3eSuggestionChip } from '@m3e/react/chips';
export { M3eNavBar, M3eNavItem } from '@m3e/react/nav-bar';
export { M3eNavRail } from '@m3e/react/nav-rail';
export { M3eAppBar } from '@m3e/react/app-bar';
export { M3eSlider, M3eSliderThumb } from '@m3e/react/slider';
export { M3eDialog, M3eDialogAction } from '@m3e/react/dialog';
export { M3eMenu, M3eMenuItem } from '@m3e/react/menu';
export { M3eList, M3eListItem, M3eActionList, M3eListAction } from '@m3e/react/list';
export { M3eSearchBar } from '@m3e/react/search';
export { M3eCard } from '@m3e/react/card';
export { M3eTabs, M3eTab, M3eTabPanel } from '@m3e/react/tabs';
export { M3eLoadingIndicator } from '@m3e/react/loading-indicator';
export { M3eLinearProgressIndicator, M3eCircularProgressIndicator } from '@m3e/react/progress-indicator';
export { M3eSwitch } from '@m3e/react/switch';
export { M3eSegmentedButton, M3eButtonSegment } from '@m3e/react/segmented-button';
export { M3eTooltip } from '@m3e/react/tooltip';
export { M3eAvatar } from '@m3e/react/avatar';
export { M3eHeading } from '@m3e/react/heading';
export { M3eBadge } from '@m3e/react/badge';
export { M3eShape } from '@m3e/react/shape';
export { M3eBottomSheet, M3eBottomSheetAction } from '@m3e/react/bottom-sheet';
export { M3eSkeleton } from '@m3e/react/skeleton';
export { M3eDivider } from '@m3e/react/divider';
export { M3eFormField } from '@m3e/react/form-field';
export { M3eSelect } from '@m3e/react/select';
export { M3eOption } from '@m3e/react/option';
export { M3eIcon } from '@m3e/react/icon';
